services:
  reverse-proxy:
    image: nginx:alpine3.19
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - frontend

  # Create frontend container
  frontend: # Name of our service
    container_name: weather-app_frontend
    build: ./frontend # path to dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/webpack.config.js:/app/webpack.config.js
    depends_on:
      - backend

  # Create backend container
  backend:
    container_name: weather-app_backend
    build: ./backend
    volumes:
      - ./backend/src:/app/src
      - ./backend/.env:/app/.env # file with key for api
